#server.error.include-stacktrace: always
logging:
  level:
    org:
      springframework: INFO
      web.filter.CommonsRequestLoggingFilter: DEBUG
    com:
      zaxxer:
        hikari: info
        hikari.HikariConfig: info

spring:
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false
  #    username: root
  #    password: root

  ## Hibernate Properties
  jpa:
    properties:
      hibernate:
        format_sql: false
    #        dialect: org.hibernate.dialect.MySQL8Dialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create

    show-sql: false