management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
springdoc:
  #  use-management-port: true
  show-actuator: true

#server.error.include-stacktrace: always
logging:
  level:
    root: info

    org:
      springframework:
        web.filter.CommonsRequestLoggingFilter: debug
        security.web.access.intercept.FilterSecurityInterceptor: trace

    com:
      zaxxer:
        hikari: info
        hikari.HikariConfig: debug

spring:
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false
  #    username: root
  #    password: root

  ## Hibernate Properties
  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect # org.hibernate.dialect.MySQL8Dialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create

graphql:
  tools:
    schema-location-pattern: "**/*.graphql"
  playground:
    mapping: /playground
    endpoint: /graphql
    subscriptionEndpoint: /subscriptions
    enabled: true
    pageTitle: Playground
    headers:
      Authorization: "Basic <your-token>"